### ISSUE TITLE
Readme on Modifying View/Style

### ISSUE THREAD

**Issue by ghost** [tjeerdintveen/Vurig-Calendar#1]
Great project! Would be good to have some additions to the Readme with a quick rundown on modifying the look/style of the calendar. Great work so far!

**Comment by tjeerdintveen** [comment]
Thanks! I'll look into it. But for now the whole drawing part is commented, so with a little bit of Quartz you can get a lot done.

**Comment by ghost** [comment]
It is very well commented :) Just a thought for those who are quickly glancing through repositories and not looking at the code right away. Thanks!

**Comment by tjeerdintveen** [comment]
Good point :-)
