### ISSUE TITLE
with table view like iPhone cal

### ISSUE THREAD

**Issue by ghost** [tjeerdintveen/Vurig-Calendar#2]
Is there ways to put this cal with a tableview like the iPhone's cal? You're example is nice but don't see how to make with tableview

thanks

**Comment by tjeerdintveen** [comment]
It's actually quite easy. Just put a tableview below the calendar. The "switched to month" method gives the new height of the calendar so you can use the remaining height as the height for the tableview.
Not attaching it to a table gives more flexibility I think.

**Comment by ghost** [comment]
I will be trying - thx

**Comment by BlackMarq20** [comment]
Hi, 

do you have an example of adjusting the height when the calendar view changes?

**Comment by tjeerdintveen** [comment]
Sorry, not at the moment. But it's not complex.
All you have to do is add a tableview. Make it the screenheight - calendar height.
